<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import type { CalculatorInputs, ScenarioType } from '../types';
  import { parseAmount, parseDuration, parseAppreciationRates } from '../lib/formatter';
  import { getMarketAverages, getLastUpdated } from '../lib/marketData';

  export let formInputs: any;

  const dispatch = createEventDispatcher();

  type FieldType = 'currency' | 'rate' | 'duration' | 'toggle' | 'text';

  interface FormField {
    key: string;
    label: string;
    help: string;
    placeholder: string;
    visible: () => boolean;
    disabled?: () => boolean;
    isHeader?: boolean;
    headerText?: string;
    toggleValues?: string[];  // For fields that can toggle between two values
    fieldType?: FieldType;
  }

  let fields: FormField[] = [];
  let currentFieldIndex = 0;
  let inputRefs: HTMLInputElement[] = [];

  $: {
    // Rebuild fields list when scenario changes
    fields = [
      { key: 'header_scenario', label: '', help: '', placeholder: '', visible: () => true, isHeader: true, headerText: 'SCENARIO SELECTION' },
      { key: 'scenario', label: 'Scenario', help: 'Select buy_vs_rent to compare buying vs renting, or sell_vs_keep to compare selling vs keeping an existing asset', placeholder: 'buy_vs_rent', visible: () => true, toggleValues: ['buy_vs_rent', 'sell_vs_keep'], fieldType: 'toggle' },

      { key: 'header_economic', label: '', help: '', placeholder: '', visible: () => true, isHeader: true, headerText: 'ECONOMIC ASSUMPTIONS' },
      { key: 'inflationRate', label: 'Inflation Rate (%)', help: 'Annual inflation for all recurring costs', placeholder: '3', visible: () => true, fieldType: 'rate' },
      { key: 'investmentReturnRate', label: 'Investment Return (%)', help: 'Expected return on investments. Market averages shown above', placeholder: '10', visible: () => true, fieldType: 'rate' },

      { key: 'header_asset', label: '', help: '', placeholder: '', visible: () => true, isHeader: true, headerText: formInputs.scenario === 'sell_vs_keep' ? 'ASSET' : 'BUYING' },
      { key: 'purchasePrice', label: formInputs.scenario === 'sell_vs_keep' ? 'Original Purchase Price' : 'Asset Purchase Price', help: formInputs.scenario === 'sell_vs_keep' ? 'What you originally paid for the asset (for capital gains)' : 'Initial purchase price of the asset', placeholder: '500k', visible: () => true, fieldType: 'currency' },
      { key: 'currentMarketValue', label: 'Current Market Value', help: 'What the asset is worth today', placeholder: '2.2m', visible: () => formInputs.scenario === 'sell_vs_keep', fieldType: 'currency' },
      { key: 'annualInsurance', label: 'Annual Tax & Insurance', help: formInputs.scenario === 'sell_vs_keep' ? 'Yearly costs if keeping' : 'Yearly insurance cost', placeholder: '3k', visible: () => true, fieldType: 'currency' },
      { key: 'annualTaxes', label: 'Other Annual Costs', help: 'Maintenance, utilities, HOA, etc.', placeholder: '5k', visible: () => true, fieldType: 'currency' },
      { key: 'annualIncome', label: 'Annual Income from Asset', help: 'Rental income or other income generated by the asset', placeholder: '0', visible: () => true, fieldType: 'currency' },
      { key: 'appreciationRate', label: 'Appreciation Rate (%)', help: formInputs.scenario === 'sell_vs_keep' ? 'Annual rate if keeping. Comma-separated for different years' : 'Annual rate (can be negative for depreciation). Comma-separated values apply to first years, last value for all remaining years (e.g., \'10,5,3\' = 10% yr1, 5% yr2, 3% yr3+)', placeholder: '3', visible: () => true, fieldType: 'rate' },

      { key: 'header_loan', label: '', help: '', placeholder: '', visible: () => true, isHeader: true, headerText: 'LOAN' },
      { key: 'includeRefinance', label: 'Include Refinance', help: 'Toggle to use refinance terms instead of existing loan', placeholder: 'no', visible: () => formInputs.scenario === 'sell_vs_keep', toggleValues: ['yes', 'no'], fieldType: 'toggle' },
      { key: 'payoffBalance', label: 'Payoff Balance', help: 'Current loan balance to pay off with refinance', placeholder: '300k', visible: () => formInputs.scenario === 'sell_vs_keep' && formInputs.includeRefinance === 'yes', fieldType: 'currency' },
      { key: 'loanAmount', label: formInputs.scenario === 'sell_vs_keep' ? (formInputs.includeRefinance === 'yes' ? 'Refinance Loan Amount' : 'Original Loan Amount') : 'Loan Amount', help: formInputs.scenario === 'sell_vs_keep' ? (formInputs.includeRefinance === 'yes' ? 'New refinance loan amount' : 'The original loan amount when purchased (we\'ll calculate remaining balance)') : 'Total mortgage/loan amount', placeholder: '400k', visible: () => true, fieldType: 'currency' },
      { key: 'loanRate', label: formInputs.includeRefinance === 'yes' ? 'Refinance Rate (%)' : 'Loan Rate (%)', help: formInputs.scenario === 'sell_vs_keep' ? (formInputs.includeRefinance === 'yes' ? 'Annual interest rate on refinance loan' : 'Annual interest rate on existing loan') : 'Annual interest rate (e.g., 6.5)', placeholder: '6.5', visible: () => true, fieldType: 'rate' },
      { key: 'loanTerm', label: formInputs.includeRefinance === 'yes' ? 'Refinance Term' : 'Loan Term', help: formInputs.scenario === 'sell_vs_keep' ? (formInputs.includeRefinance === 'yes' ? 'Refinance loan duration (e.g., 30y)' : 'Original loan duration when started (e.g., 30y)') : 'Loan duration (e.g., 5y, 30y)', placeholder: '30y', visible: () => true, fieldType: 'duration' },
      { key: 'remainingLoanTerm', label: 'Remaining Loan Term', help: 'Time left on loan (e.g., 25y)', placeholder: '25y', visible: () => formInputs.scenario === 'sell_vs_keep' && formInputs.includeRefinance !== 'yes', fieldType: 'duration' },
      { key: 'closingCosts', label: 'Refinance Closing Costs', help: 'Closing costs for refinance (negative if getting cash back)', placeholder: '5k', visible: () => formInputs.scenario === 'sell_vs_keep' && formInputs.includeRefinance === 'yes', fieldType: 'currency' },

      { key: 'header_renting', label: '', help: '', placeholder: '', visible: () => true, isHeader: true, headerText: 'RENTING' },
      { key: 'includeRentingSell', label: 'Include Renting Analysis', help: 'Toggle if selling means you\'ll need to rent', placeholder: 'no', visible: () => formInputs.scenario === 'sell_vs_keep', toggleValues: ['yes', 'no'], fieldType: 'toggle' },
      { key: 'rentDeposit', label: 'Rental Deposit', help: formInputs.scenario === 'sell_vs_keep' ? 'Initial rental deposit if selling' : 'Initial rental deposit', placeholder: '5k', visible: () => true, disabled: () => formInputs.scenario === 'sell_vs_keep' && formInputs.includeRentingSell !== 'yes', fieldType: 'currency' },
      { key: 'monthlyRent', label: 'Monthly Rent', help: formInputs.scenario === 'sell_vs_keep' ? 'Monthly rent if selling' : 'Base monthly rent amount', placeholder: '3k', visible: () => true, disabled: () => formInputs.scenario === 'sell_vs_keep' && formInputs.includeRentingSell !== 'yes', fieldType: 'currency' },
      { key: 'annualRentCosts', label: 'Annual Rent Costs', help: formInputs.scenario === 'sell_vs_keep' ? 'Yearly rental costs if selling' : 'Yearly rental-related costs', placeholder: '1k', visible: () => true, disabled: () => formInputs.scenario === 'sell_vs_keep' && formInputs.includeRentingSell !== 'yes', fieldType: 'currency' },
      { key: 'otherAnnualCosts', label: 'Other Annual Costs', help: 'Additional yearly costs for renting', placeholder: '500', visible: () => formInputs.scenario === 'buy_vs_rent', fieldType: 'currency' },

      { key: 'header_selling', label: '', help: '', placeholder: '', visible: () => true, isHeader: true, headerText: 'SELLING' },
      { key: 'includeSelling', label: 'Include Selling Analysis', help: 'Toggle to enable/disable selling analysis', placeholder: 'no', visible: () => true, toggleValues: ['yes', 'no'], disabled: () => formInputs.scenario === 'sell_vs_keep', fieldType: 'toggle' },
      { key: 'agentCommission', label: 'Agent Commission (%)', help: 'Percentage of sale price paid to agents', placeholder: '6', visible: () => true, disabled: () => formInputs.includeSelling !== 'yes', fieldType: 'rate' },
      { key: 'stagingCosts', label: 'Staging/Selling Costs', help: 'Fixed costs to prepare and sell', placeholder: '10k', visible: () => true, disabled: () => formInputs.includeSelling !== 'yes', fieldType: 'currency' },
      { key: 'taxFreeLimits', label: 'Tax-Free Gains Limit', help: 'Capital gains exempt from tax. Comma-separated for different years (e.g., \'500k,0k\' = 500k year 1, 0 year 2+)', placeholder: '250k', visible: () => true, disabled: () => formInputs.includeSelling !== 'yes', fieldType: 'currency' },
      { key: 'capitalGainsTax', label: 'Capital Gains Tax (%)', help: 'Long-term capital gains tax rate', placeholder: '20', visible: () => true, disabled: () => formInputs.includeSelling !== 'yes', fieldType: 'rate' },
    ];
  }

  // Auto-set includeSelling to 'yes' in sell_vs_keep scenario
  $: {
    if (formInputs.scenario === 'sell_vs_keep') {
      formInputs.includeSelling = 'yes';
    }
  }

  $: visibleFields = fields.filter(f => f.visible());
  $: currentHelpText = visibleFields[currentFieldIndex]?.help || '';
  $: currentFieldType = visibleFields[currentFieldIndex]?.fieldType;
  $: fieldTypeHint = currentFieldType === 'currency'
    ? 'use k for thousand, m for million (e.g., 5k, 2.5m)'
    : currentFieldType === 'duration'
    ? 'use y for years, m for months (e.g., 29y6m)'
    : currentFieldType === 'toggle'
    ? 'tap to toggle, or use ← → arrow keys'
    : '';

  // Market averages for investment return rate field
  const marketAvg = getMarketAverages();

  function handleKeyDown(event: KeyboardEvent) {
    // Ignore if a dialog is open
    if (document.querySelector('.dialog-overlay')) {
      return;
    }

    const currentField = visibleFields[currentFieldIndex];

    if (event.key === 'ArrowDown') {
      event.preventDefault();
      moveToNextField();
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      moveToPreviousField();
    } else if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
      // Toggle value for fields with toggleValues
      if (currentField && currentField.toggleValues && currentField.toggleValues.length === 2) {
        event.preventDefault();
        toggleFieldValue(currentField);
      }
    } else if (event.key === 'Enter') {
      event.preventDefault();
      if (event.ctrlKey) {
        handleSubmit();
      } else {
        // Regular Enter just moves to next field
        moveToNextField();
      }
    } else if (event.key === 'k' && event.ctrlKey) {
      event.preventDefault();
      handleSubmit();
    } else if (event.key === 'Tab') {
      event.preventDefault();
      if (event.shiftKey) {
        moveToPreviousField();
      } else {
        moveToNextField();
      }
    }
  }

  function toggleFieldValue(field: FormField) {
    if (!field.toggleValues || field.toggleValues.length !== 2) return;

    const currentValue = formInputs[field.key];
    const [value1, value2] = field.toggleValues;

    // Toggle to the other value
    formInputs[field.key] = currentValue === value1 ? value2 : value1;
  }

  function handleToggleClick(field: FormField) {
    if (field.toggleValues && field.toggleValues.length === 2) {
      toggleFieldValue(field);
    }
  }

  function moveToNextField() {
    // Validate current field before moving
    const currentField = visibleFields[currentFieldIndex];
    if (currentField && !currentField.isHeader) {
      validateAndResetField(currentField);
    }

    let nextIndex = currentFieldIndex + 1;
    // Skip headers and disabled fields
    while (nextIndex < visibleFields.length && (visibleFields[nextIndex].isHeader || (visibleFields[nextIndex].disabled && visibleFields[nextIndex].disabled()))) {
      nextIndex++;
    }
    if (nextIndex < visibleFields.length) {
      currentFieldIndex = nextIndex;
      focusCurrentField();
    }
  }

  function moveToPreviousField() {
    // Validate current field before moving
    const currentField = visibleFields[currentFieldIndex];
    if (currentField && !currentField.isHeader) {
      validateAndResetField(currentField);
    }

    let prevIndex = currentFieldIndex - 1;
    // Skip headers and disabled fields
    while (prevIndex >= 0 && (visibleFields[prevIndex].isHeader || (visibleFields[prevIndex].disabled && visibleFields[prevIndex].disabled()))) {
      prevIndex--;
    }
    if (prevIndex >= 0) {
      currentFieldIndex = prevIndex;
      focusCurrentField();
    }
  }

  function focusCurrentField() {
    setTimeout(() => {
      const input = inputRefs[currentFieldIndex];
      if (input) {
        input.focus();
        input.select();
        // Always scroll to center for consistent behavior
        input.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
    }, 0);
  }

  function handleFieldFocus(index: number) {
    currentFieldIndex = index;
  }

  function convertFormInputsToCalculatorInputs(): CalculatorInputs {
    return {
      scenario: formInputs.scenario as ScenarioType,
      inflationRate: parseFloat(formInputs.inflationRate) || 0,
      investmentReturnRate: parseFloat(formInputs.investmentReturnRate) || 0,
      include30Year: formInputs.include30Year === 'yes' || formInputs.include30Year === true,
      purchasePrice: parseAmount(formInputs.purchasePrice.toString()),
      currentMarketValue: formInputs.currentMarketValue ? parseAmount(formInputs.currentMarketValue.toString()) : undefined,
      annualInsurance: parseAmount(formInputs.annualInsurance.toString()),
      annualTaxes: parseAmount(formInputs.annualTaxes.toString()),
      annualIncome: parseAmount(formInputs.annualIncome.toString()),
      appreciationRate: parseAppreciationRates(formInputs.appreciationRate),
      includeRefinance: formInputs.includeRefinance === 'yes' || formInputs.includeRefinance === true,
      payoffBalance: formInputs.payoffBalance ? parseAmount(formInputs.payoffBalance.toString()) : undefined,
      loanAmount: parseAmount(formInputs.loanAmount.toString()),
      loanRate: parseFloat(formInputs.loanRate) || 0,
      loanTerm: parseDuration(formInputs.loanTerm),
      remainingLoanTerm: formInputs.remainingLoanTerm ? parseDuration(formInputs.remainingLoanTerm) : undefined,
      closingCosts: formInputs.closingCosts ? parseAmount(formInputs.closingCosts.toString()) : undefined,
      rentDeposit: parseAmount(formInputs.rentDeposit.toString()),
      monthlyRent: parseAmount(formInputs.monthlyRent.toString()),
      annualRentCosts: parseAmount(formInputs.annualRentCosts.toString()),
      otherAnnualCosts: parseAmount(formInputs.otherAnnualCosts.toString()),
      includeSelling: formInputs.includeSelling === 'yes' || formInputs.includeSelling === true,
      includeRentingSell: formInputs.includeRentingSell === 'yes' || formInputs.includeRentingSell === true,
      agentCommission: parseFloat(formInputs.agentCommission) || 0,
      stagingCosts: parseAmount(formInputs.stagingCosts.toString()),
      taxFreeLimits: parseAppreciationRates(formInputs.taxFreeLimits),
      capitalGainsTax: parseFloat(formInputs.capitalGainsTax) || 0,
    };
  }

  function handleSubmit() {
    try {
      const inputs = convertFormInputsToCalculatorInputs();
      dispatch('calculate', inputs);
    } catch (error) {
      alert(`Invalid input: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  function handleContainerClick() {
    // Refocus current field when clicking anywhere in the container
    focusCurrentField();
  }

  function validateAndResetField(field: FormField) {
    // Skip validation for toggle fields
    if (field.toggleValues) {
      return;
    }

    const value = formInputs[field.key];

    // Skip empty values
    if (!value || value.trim() === '') {
      return;
    }

    // Fields that use parseDuration
    const durationFields = ['loanTerm', 'remainingLoanTerm'];
    if (durationFields.includes(field.key)) {
      try {
        parseDuration(value);
      } catch (error) {
        formInputs[field.key] = '0';
      }
      return;
    }

    // Fields that use parseAppreciationRates (comma-separated)
    const arrayFields = ['appreciationRate', 'taxFreeLimits'];
    if (arrayFields.includes(field.key)) {
      // Check if input contains at least one digit
      if (!/\d/.test(value)) {
        formInputs[field.key] = '0';
      }
      return;
    }

    // Fields that use parseFloat (percentages)
    const percentFields = ['inflationRate', 'investmentReturnRate', 'loanRate', 'agentCommission', 'capitalGainsTax'];
    if (percentFields.includes(field.key)) {
      const parsed = parseFloat(value);
      if (isNaN(parsed)) {
        formInputs[field.key] = '0';
      }
      return;
    }

    // All other fields use parseAmount (currency fields)
    // Check if the input contains at least one digit
    if (!/\d/.test(value)) {
      formInputs[field.key] = '0';
    }
  }

  function handleGlobalKeyDown(event: KeyboardEvent) {
    // Ignore if a dialog is open (check for dialog overlay)
    if (document.querySelector('.dialog-overlay')) {
      return;
    }

    // Capture arrow keys globally to prevent page scrolling
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp' || event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
      // If no input is focused, focus the current field
      const activeElement = document.activeElement;
      const isInputFocused = inputRefs.some(ref => ref === activeElement);
      if (!isInputFocused) {
        event.preventDefault();
        focusCurrentField();
      }
    }
  }

  onMount(() => {
    // Find first non-header, non-disabled field to focus
    let firstFieldIndex = 0;
    while (firstFieldIndex < visibleFields.length &&
           (visibleFields[firstFieldIndex].isHeader ||
            (visibleFields[firstFieldIndex].disabled && visibleFields[firstFieldIndex].disabled()))) {
      firstFieldIndex++;
    }
    currentFieldIndex = firstFieldIndex;
    focusCurrentField();

    // Add global keyboard handler
    window.addEventListener('keydown', handleGlobalKeyDown);

    return () => {
      window.removeEventListener('keydown', handleGlobalKeyDown);
    };
  });
</script>

<div class="terminal-container font-mono" on:click={handleContainerClick}>
  <div class="terminal-content">
    <form on:submit|preventDefault={handleSubmit} class="space-y-1">
    {#each visibleFields as field, index}
      {#if field.isHeader}
        <div class="section-header">
          <span class="text-light-orange dark:text-monokai-orange">{field.headerText}</span>
        </div>
        {#if field.key === 'header_economic'}
          <div class="market-averages-inline">
            <span class="text-light-text-muted dark:text-monokai-text-muted">Market Avg (10y): </span>
            <span class="text-light-cyan dark:text-monokai-cyan">Inflation</span> {marketAvg.inflation.toFixed(1)}% ·
            <span class="text-light-cyan dark:text-monokai-cyan">VOO</span> {marketAvg.voo.toFixed(1)}% ·
            <span class="text-light-cyan dark:text-monokai-cyan">QQQ</span> {marketAvg.qqq.toFixed(1)}% ·
            <span class="text-light-cyan dark:text-monokai-cyan">VTI</span> {marketAvg.vti.toFixed(1)}% ·
            <span class="text-light-cyan dark:text-monokai-cyan">BND</span> {marketAvg.bnd.toFixed(1)}% ·
            <span class="text-light-cyan dark:text-monokai-cyan">60/40</span> {marketAvg.mix6040.toFixed(1)}%
            <span class="text-light-text-muted dark:text-monokai-text-muted ml-2">(Updated {new Date(getLastUpdated()).toLocaleDateString('en-US', { month: 'short', year: 'numeric' })})</span>
          </div>
        {/if}
      {:else}
        <div class="terminal-field" class:focused={index === currentFieldIndex} class:disabled={field.disabled && field.disabled()}>
          <div class="flex flex-col md:flex-row md:items-center gap-1 md:gap-2">
            <div class="field-label md:w-72 md:flex-shrink-0">
              <span class="text-light-pink dark:text-monokai-pink">{index === currentFieldIndex ? '>' : ' '}</span>
              <span class="ml-2" class:text-light-pink={index === currentFieldIndex} class:dark:text-monokai-pink={index === currentFieldIndex} class:text-light-text={index !== currentFieldIndex} class:dark:text-monokai-text={index !== currentFieldIndex}>{field.label}:</span>
            </div>
            <div class="field-input flex-1 min-w-0 ml-6 md:ml-0">
              {#if field.fieldType === 'toggle'}
                <button
                  type="button"
                  bind:this={inputRefs[index]}
                  on:keydown={handleKeyDown}
                  on:focus={() => handleFieldFocus(index)}
                  on:blur={() => validateAndResetField(field)}
                  on:click={() => handleToggleClick(field)}
                  class="terminal-input terminal-input-toggle w-full text-left"
                  disabled={field.disabled && field.disabled()}
                >{formInputs[field.key] || field.placeholder}</button>
              {:else}
                <input
                  type="text"
                  bind:value={formInputs[field.key]}
                  bind:this={inputRefs[index]}
                  on:keydown={handleKeyDown}
                  on:focus={() => handleFieldFocus(index)}
                  on:blur={() => validateAndResetField(field)}
                  placeholder={field.placeholder}
                  class="terminal-input w-full"
                  disabled={field.disabled && field.disabled()}
                />
              {/if}
            </div>
          </div>
          <!-- Inline help text -->
          <div class="field-help-inline" class:focused={index === currentFieldIndex}>
            <span>{field.help}</span>
            {#if field.fieldType === 'currency'}
              <span> | use k for thousand, m for million (e.g., 5k, 2.5m)</span>
            {:else if field.fieldType === 'duration'}
              <span> | use y for years, m for months (e.g., 29y6m)</span>
            {:else if field.fieldType === 'toggle'}
              <span> | tap to toggle</span>
            {/if}
          </div>
        </div>
      {/if}
    {/each}

    </form>
  </div>

  <!-- Keyboard shortcuts - Desktop -->
  <div class="help-section">
    <div class="help-nav">
      <span class="text-light-cyan dark:text-monokai-cyan">↑↓←→</span> navigate | <span class="text-light-cyan dark:text-monokai-cyan">Ctrl+S</span> <button type="button" on:click={() => dispatch('save')} class="secondary-button-bar">Save</button> | <span class="text-light-cyan dark:text-monokai-cyan">Ctrl+O</span> <button type="button" on:click={() => dispatch('load')} class="secondary-button-bar">Load</button> | <span class="text-light-cyan dark:text-monokai-cyan">Ctrl+K / Ctrl+Enter</span> <button type="button" on:click={handleSubmit} class="calculate-button-bar">Calculate</button>
    </div>
  </div>
</div>

<style>
  .terminal-container {
    @apply bg-light-bg dark:bg-black;
    padding: 0.5rem;
    @apply border-2 border-light-border dark:border-monokai-border;
    border-radius: 0.5rem;
    max-width: 100%;
    overflow-x: hidden;
  }

  @media (min-width: 768px) {
    .terminal-container {
      padding: 1rem;
      padding-bottom: 3rem; /* Space for fixed help section */
    }
  }

  .terminal-content {
    padding-right: 0.5rem;
    padding-bottom: 0.5rem;
    max-width: 100%;
  }

  .terminal-field {
    padding: 0.125rem 0.5rem;
    transition: all 0.15s;
    border-left: 2px solid transparent;
    font-size: 14px;
    max-width: 100%;
    overflow: hidden;
  }

  @media (min-width: 768px) {
    .terminal-field {
      padding: 0.125rem 0.75rem;
      font-size: 0.875rem;
    }
  }

  .terminal-field.focused {
    border-left-color: #D91B5B;
    background-color: #f4f4f5;
  }

  :global(.dark) .terminal-field.focused {
    border-left-color: #FF6188;
    background-color: transparent;
  }

  .terminal-field.disabled {
    opacity: 0.4;
    pointer-events: none;
  }

  .field-label {
    font-size: 14px;
    font-weight: 600;
    word-break: break-word;
    overflow-wrap: break-word;
  }

  @media (min-width: 768px) {
    .field-label {
      font-size: 0.875rem;
    }
  }

  .terminal-input {
    background: transparent;
    border: none;
    outline: none;
    @apply text-light-text dark:text-monokai-text;
    font-family: 'JetBrains Mono', monospace;
    font-size: 16px; /* Must be 16px or larger to prevent mobile zoom */
    font-weight: 600;
    padding: 0.1rem 0;
    max-width: 100%;
    box-sizing: border-box;
  }

  @media (min-width: 768px) {
    .terminal-input {
      font-size: 0.875rem;
    }
  }

  .terminal-input-toggle {
    cursor: pointer;
    user-select: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    caret-color: transparent;
    -webkit-touch-callout: none;
    touch-action: manipulation;
  }

  .terminal-input-toggle:focus {
    outline: none;
  }

  :global(.dark) .terminal-input::placeholder {
    color: #5c5c5c;
    font-style: italic;
  }

  :global(:not(.dark)) .terminal-input::placeholder {
    color: #a1a1aa;
    font-style: italic;
  }

  .section-header {
    margin-top: 0.5rem;
    margin-bottom: 0.125rem;
    padding: 0.125rem 0.5rem;
    font-weight: 700;
    font-size: 12px;
    letter-spacing: 0.05em;
    @apply border-b border-light-border dark:border-monokai-border;
  }

  @media (min-width: 768px) {
    .section-header {
      padding: 0.125rem 0.75rem;
      font-size: 0.8125rem;
    }
  }

  .field-help-inline {
    display: none;
    margin-top: 0.25rem;
    margin-left: 1.5rem;
    padding: 0.25rem 0.5rem;
    font-size: 11px;
    line-height: 1.4;
    font-weight: 600;
    @apply text-light-text-muted dark:text-monokai-text-muted;
  }

  .field-help-inline.focused {
    display: block;
  }

  @media (min-width: 768px) {
    .field-help-inline {
      margin-left: 2.25rem;
      font-size: 0.75rem;
    }
  }

  .help-section {
    display: none;
  }

  @media (min-width: 768px) {
    .help-section {
      display: block;
      position: fixed;
      bottom: 0;
      left: 50%;
      transform: translateX(-50%);
      width: 100%;
      max-width: 80rem; /* max-w-7xl to match container */
      padding: 0.5rem 2rem;
      @apply bg-light-bg-light dark:bg-[#0a0a0a];
      @apply border-t border-light-border dark:border-monokai-border;
      overflow: hidden;
      z-index: 10;
    }
  }

  .help-nav {
    @apply text-light-text dark:text-monokai-text;
    font-size: 0.8125rem;
    font-weight: 600;
    line-height: 1.3;
  }

  .market-averages-inline {
    padding: 0.125rem 0.5rem 0.125rem 1.5rem;
    font-size: 12px;
    font-weight: 600;
    @apply text-light-text dark:text-monokai-text;
    max-width: 100%;
    overflow: hidden;
  }

  @media (min-width: 768px) {
    .market-averages-inline {
      padding: 0.125rem 0.75rem 0.125rem 2.25rem;
      font-size: 0.8125rem;
    }
  }

  .calculate-button-bar {
    @apply bg-light-pink dark:bg-monokai-pink;
    @apply text-white;
    font-family: inherit;
    font-size: 0.75rem;
    font-weight: 600;
    padding: 0.25rem 0.75rem;
    border: none;
    border-radius: 0.25rem;
    cursor: pointer;
    transition: opacity 0.15s ease;
    margin-left: 0.25rem;
  }

  .calculate-button-bar:hover {
    opacity: 0.9;
  }

  .calculate-button-bar:active {
    opacity: 0.8;
  }

  .secondary-button-bar {
    @apply bg-zinc-600 dark:bg-zinc-600;
    @apply text-white;
    font-family: inherit;
    font-size: 0.75rem;
    font-weight: 600;
    padding: 0.25rem 0.75rem;
    border: none;
    border-radius: 0.25rem;
    cursor: pointer;
    transition: opacity 0.15s ease;
    margin-left: 0.25rem;
  }

  .secondary-button-bar:hover {
    opacity: 0.9;
  }

  .secondary-button-bar:active {
    opacity: 0.8;
  }

</style>
